### ISSUE TITLE
Resolving Plugin-Related Issue: Deprecated 'package' Attribute in AndroidManifest.xml

### ISSUE THREAD

**Issue by 18126171** [nguyenphuc22/Android-Package-Renamer#4]
Hi Phuc,

I encountered an issue related to a plugin that changes the package name in an Android app. After using the plugin, everything seems to work well, but during the build process, the IDE displays the following message: "package="vn.com.gatrongqwe.modulesone" found in source AndroidManifest.xml: C:\Users\nickseven\AndroidStudioProjects\TestModules\app\modulesone\src\main\AndroidManifest.xml. Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored."

My recommendation to resolve this issue is to remove the line "package="vn.com.gatrongqwe.modulesone" from the source AndroidManifest.xml file located at C:\Users\nickseven\AndroidStudioProjects\TestModules\app\modulesone\src\main\AndroidManifest.xml.

Hope this helps! Let me know if you need further assistance.

**Comment by nguyenphuc22** [comment]
Hello,

I have received the notification about the issue and confirmed it. I will fix it as soon as possible. Thank you for reporting this.

**Comment by 18126171** [comment]
I tested the new version according to your link. It's been solved
